# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8724fbe1102fe24cda4d2b4543eb33187ff4e2c096a0f2a9db0158802652f798d1693cd6a61a07967e82e968ec433c83e83ad8246542ad37010fc7be0f38cb31

test:
  secret_key_base: f5239896e291b84a9c6806cc0830fdda20960fc8e5818cd0e2b7626bd32200a8aba5b4fa1a9cec5c34131057c856ebbdb2ed941f6c5dd4b07c7cf41cde0a8b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
